# Configurações de Banco de Dados (Testes)
spring.datasource.url=jdbc:postgresql://localhost:5433/codexia_test
spring.datasource.username=codexia
spring.datasource.password=codexia

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Garante que o banco seja limpo antes de cada execução de teste se necessário
spring.flyway.clean-disabled=false


# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true